### ISSUE TITLE
AttributeErro

### ISSUE THREAD

**Issue by kunpeng9** [abdnh/anki-deck-last-review-time#1]
运行出错。请在启动Anki时按住「Shift」键以临时禁用插件加载。 如仅在插件启用时出错，请使用「工具」>「插件」功能禁用部分插件后重启Anki，请重复上述步骤找出引起错误的插件并反馈给插件作者。 调试信息：
Anki 2.1.63 (f356f177) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-07-03 18:24:36
Traceback (most recent call last):
  File "aqt.main", line 609, in loadCollection
  File "aqt.main", line 712, in moveToState
  File "aqt.main", line 718, in _deckBrowserState
  File "aqt.deckbrowser", line 70, in show
  File "aqt.deckbrowser", line 149, in _renderPage
  File "aqt.deckbrowser", line 158, in __renderPage
  File "_aqt.hooks", line 1669, in __call__
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\504609572\__init__.py", line 34, in add_last_review_time
    soup.select_one(".optscol").insert_before(th)
AttributeError: 'NoneType' object has no attribute 'insert_before'

**Comment by abdnh** [comment]
I can't reproduce this. Are you using any other add-ons that also modify the deck list? Can you post a screenshot of your add-on list?

**Comment by kunpeng9** [comment]
> I can't reproduce this. Are you using any other add-ons that also modify the deck list? Can you post a screenshot of your add-on list?

![天若_20230707193213](https://github.com/abdnh/anki-deck-last-review-time/assets/44609485/ffeae5cf-d988-4b0d-a57f-be55e9c6c805)

**Comment by abdnh** [comment]
The add-on is not compatible with the "Enhance main window" add-on at the moment. I might support it in the future so I'll leave this issue open.
